# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hub.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\thub.proto\"7\n\x0fProviderRequest\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x12\n\nauth_token\x18\x02 \x01(\t\"\x84\x01\n\nTaskResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t\x12\x12\n\nauth_token\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\t\x12\x0f\n\x07payload\x18\x06 \x01(\t\x12\x0e\n\x06result\x18\x07 \x01(\t\"\x8d\x01\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12#\n\x07\x61\x63\x63ount\x18\x04 \x03(\x0b\x32\x12.Task.AccountEntry\x1a.\n\x0c\x41\x63\x63ountEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32U\n\x03Hub\x12$\n\x07GetTask\x12\x10.ProviderRequest\x1a\x05.Task\"\x00\x12(\n\x10SubmitTaskResult\x12\x0b.TaskResult\x1a\x05.Task\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK_ACCOUNTENTRY']._loaded_options = None
  _globals['_TASK_ACCOUNTENTRY']._serialized_options = b'8\001'
  _globals['_PROVIDERREQUEST']._serialized_start=13
  _globals['_PROVIDERREQUEST']._serialized_end=68
  _globals['_TASKRESULT']._serialized_start=71
  _globals['_TASKRESULT']._serialized_end=203
  _globals['_TASK']._serialized_start=206
  _globals['_TASK']._serialized_end=347
  _globals['_TASK_ACCOUNTENTRY']._serialized_start=301
  _globals['_TASK_ACCOUNTENTRY']._serialized_end=347
  _globals['_HUB']._serialized_start=349
  _globals['_HUB']._serialized_end=434
# @@protoc_insertion_point(module_scope)
